<?php

namespace App\Filament\Resources;

use App\Filament\Resources\AttributeResource\Pages;
use App\Models\Attribute;
use App\Models\EntityType;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Schemas\Schema;
use UnitEnum;
use BackedEnum;

class AttributeResource extends Resource
{
    protected static ?string $model = Attribute::class;

    protected static string|BackedEnum|null $navigationIcon = 'heroicon-o-adjustments-horizontal';
    protected static string|UnitEnum|null $navigationGroup = 'Settings';
    protected static ?int $navigationSort = 2;

    public static function form(Schema $schema): Schema
    {
        return $schema->components([
            Forms\Components\Select::make('entity_type_id')
                ->label('Entity Type')
                ->options(EntityType::pluck('name', 'id'))
                ->required()
                ->reactive(),
            Forms\Components\TextInput::make('name')
                ->required()
                ->unique(ignoreRecord: true)
                ->helperText('Internal attribute code (e.g., product_name)'),
            Forms\Components\TextInput::make('display_name')
                ->label('Display Name')
                ->nullable()
                ->helperText('Human-readable name shown in forms (e.g., Product Name). Leave empty to auto-generate from name.'),
            Forms\Components\Select::make('attribute_section_id')
                ->label('Attribute Section')
                ->options(function (callable $get) {
                    $entityTypeId = $get('entity_type_id');
                    if (!$entityTypeId) {
                        return [];
                    }
                    return \App\Models\AttributeSection::where('entity_type_id', $entityTypeId)
                        ->orderBy('sort_order')
                        ->pluck('name', 'id');
                })
                ->searchable()
                ->nullable()
                ->helperText('Optional: Group this attribute under a section'),
            Forms\Components\TextInput::make('sort_order')
                ->numeric()
                ->default(0)
                ->required()
                ->helperText('Controls the display order within the section. Lower numbers appear first.'),
            Forms\Components\Select::make('data_type')
                ->options([
                    'integer' => 'Integer',
                    'text' => 'Text',
                    'html' => 'HTML',
                    'json' => 'JSON',
                    'select' => 'Select',
                    'multiselect' => 'Multiselect',
                    'belongs_to' => 'Belongs to',
                    'belongs_to_multi' => 'Belongs to (multi)',
                ])
                ->required()
                ->reactive(),
            Forms\Components\Select::make('editable')
                ->options([
                    'yes' => 'Yes - Directly editable',
                    'no' => 'No - Read-only',
                    'overridable' => 'Overridable - Show current value, allow override',
                ])
                ->default('yes')
                ->required()
                ->reactive()
                ->helperText('Controls whether users can edit this attribute in the UI'),
            Forms\Components\Select::make('is_pipeline')
                ->label('Is Pipeline Generated')
                ->options([
                    'yes' => 'Yes - Generated by AI/automation pipeline',
                    'no' => 'No - Manual or synced data',
                ])
                ->default('no')
                ->required()
                ->reactive()
                ->helperText('Placeholder for future pipeline integration'),
            Forms\Components\Select::make('is_sync')
                ->label('Sync Direction')
                ->options([
                    'no' => 'No sync - SPIM only',
                    'from_external' => 'From external - Read from Magento',
                    'to_external' => 'To external - Write to Magento',
                    'bidirectional' => 'Bidirectional - Two-way sync with conflict detection',
                ])
                ->default('no')
                ->required()
                ->reactive()
                ->helperText('Controls synchronization with external systems'),
            Forms\Components\Select::make('needs_approval')
                ->options([
                    'yes' => 'Yes - Always require approval',
                    'only_low_confidence' => 'Only low confidence - Require approval when confidence < 0.8',
                    'no' => 'No - Auto-approve all changes',
                ])
                ->default('no')
                ->required()
                ->reactive()
                ->helperText('Controls the approval workflow for this attribute'),
            Forms\Components\Placeholder::make('validation_warnings')
                ->label('Configuration Warnings')
                ->content(function (callable $get) {
                    $warnings = [];
                    $editable = $get('editable');
                    $isPipeline = $get('is_pipeline');
                    $isSync = $get('is_sync');
                    $needsApproval = $get('needs_approval');

                    // Rule 1: Cannot have (editable='yes' OR editable='overridable') + is_sync='from_external'
                    if (in_array($editable, ['yes', 'overridable']) && $isSync === 'from_external') {
                        $warnings[] = '⚠️ Attributes synced from external systems cannot be editable or overridable.';
                    }

                    // Rule 2: Cannot have is_pipeline='yes' + editable='yes'
                    if ($isPipeline === 'yes' && $editable === 'yes') {
                        $warnings[] = '⚠️ Pipeline attributes cannot be directly editable. Use editable="overridable" instead.';
                    }

                    // Rule 3: Cannot have needs_approval + is_sync='from_external'
                    if (in_array($needsApproval, ['yes', 'only_low_confidence']) && $isSync === 'from_external') {
                        $warnings[] = '⚠️ Attributes synced from external systems cannot require approval.';
                    }

                    if (empty($warnings)) {
                        return '✓ Configuration is valid';
                    }

                    return implode("\n", $warnings);
                })
                ->visible(fn (callable $get) =>
                    $get('editable') !== null ||
                    $get('is_pipeline') !== null ||
                    $get('is_sync') !== null ||
                    $get('needs_approval') !== null
                ),
            Forms\Components\KeyValue::make('allowed_values')
                ->visible(fn (callable $get) => in_array($get('data_type'), ['select','multiselect'], true))
                ->helperText('Dictionary of KEY => Label'),
            Forms\Components\Select::make('linked_entity_type_id')
                ->label('Linked Entity Type')
                ->options(EntityType::pluck('name', 'id'))
                ->visible(fn (callable $get) => in_array($get('data_type'), ['belongs_to','belongs_to_multi'], true)),
            Forms\Components\TextInput::make('ui_class')
                ->nullable()
                ->helperText('Custom UI handler class (optional)'),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('entityType.name')->sortable()->label('Entity Type'),
                Tables\Columns\TextColumn::make('name')->searchable()->sortable(),
                Tables\Columns\BadgeColumn::make('data_type'),
                Tables\Columns\BadgeColumn::make('editable'),
                Tables\Columns\BadgeColumn::make('is_sync')->label('Sync'),
                Tables\Columns\BadgeColumn::make('needs_approval')->label('Approval'),
                Tables\Columns\IconColumn::make('is_pipeline')
                    ->boolean()
                    ->label('Pipeline')
                    ->trueIcon('heroicon-o-cog')
                    ->falseIcon('heroicon-o-minus'),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('entity_type_id')
                    ->options(EntityType::pluck('name', 'id')),
                Tables\Filters\SelectFilter::make('data_type')
                    ->options([
                        'integer' => 'Integer',
                        'text' => 'Text',
                        'html' => 'HTML',
                        'json' => 'JSON',
                        'select' => 'Select',
                        'multiselect' => 'Multiselect',
                        'belongs_to' => 'Belongs to',
                        'belongs_to_multi' => 'Belongs to (multi)',
                    ]),
                Tables\Filters\SelectFilter::make('is_sync')
                    ->options([
                        'no' => 'No sync',
                        'from_external' => 'From external',
                        'to_external' => 'To external',
                        'bidirectional' => 'Bidirectional',
                    ]),
                Tables\Filters\SelectFilter::make('editable')
                    ->options([
                        'yes' => 'Yes',
                        'no' => 'No',
                        'overridable' => 'Overridable',
                    ]),
            ])
            ->actions([
                EditAction::make(),
            ])
            ->bulkActions([
                DeleteBulkAction::make(),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListAttributes::route('/'),
            'create' => Pages\CreateAttribute::route('/create'),
            'edit' => Pages\EditAttribute::route('/{record}/edit'),
        ];
    }
}
